services:
  hub:
    image: selenium/hub:4.32
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:4.32
    shm_size: 2g
    deploy: 
      replicas: 1
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.32
    shm_size: 2g
    deploy: 
      replicas: 0
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  